//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public Chat()
        {
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int ID_Chat { get; set; }
        public int Usuario1 { get; set; }
        public int Usuario2 { get; set; }
    
        public virtual Usuario UsuarioN1 { get; set; }
        public virtual Usuario UsuarioN2 { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
    }
}
