//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.IntegranteDeGrupo = new HashSet<IntegranteDeGrupo>();
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int ID_Grupo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<IntegranteDeGrupo> IntegranteDeGrupo { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
    }
}
