//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegranteDeGrupo
    {
        public int ID_Grupo { get; set; }
        public int ID_Integrante { get; set; }
        public bool esAdmin { get; set; }
        public int ID_Grupo_Integrante { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
