//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMRGScrollEntities : DbContext
    {
        public SMRGScrollEntities()
            : base("name=SMRGScrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chat { get; set; }
        public DbSet<Emoji> Emoji { get; set; }
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<IntegranteDeGrupo> IntegranteDeGrupo { get; set; }
        public DbSet<Mensaje> Mensaje { get; set; }
        public DbSet<SolicitudDeAmistad> SolicitudDeAmistad { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
