//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDeAmistad
    {
        public int ID_Solicitud { get; set; }
        public int uEmisor { get; set; }
        public int uReceptor { get; set; }
    
        public virtual Usuario UsuarioEmisor { get; set; }
        public virtual Usuario UsuarioReceptor { get; set; }
    }
}
