//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGRScroll_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ChatUsuario1 = new HashSet<Chat>();
            this.ChatUsurio2 = new HashSet<Chat>();
            this.IntegranteDeGrupo = new HashSet<IntegranteDeGrupo>();
            this.Mensaje = new HashSet<Mensaje>();
            this.SolicitudEmisor = new HashSet<SolicitudDeAmistad>();
            this.SolicitudReceptor = new HashSet<SolicitudDeAmistad>();
        }
    
        public int ID_Usuario { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string nickName { get; set; }
        public string estadoTexto { get; set; }
        public Nullable<int> estado { get; set; }
        public string numeroAmigo { get; set; }
        public byte[] imagenAvatar { get; set; }
    
        public virtual ICollection<Chat> ChatUsuario1 { get; set; }
        public virtual ICollection<Chat> ChatUsurio2 { get; set; }
        public virtual ICollection<IntegranteDeGrupo> IntegranteDeGrupo { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        public virtual ICollection<SolicitudDeAmistad> SolicitudEmisor { get; set; }
        public virtual ICollection<SolicitudDeAmistad> SolicitudReceptor { get; set; }
    }
}
